// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCos_d-Gq0BikyEEASP3APZM8ZMrnrgEmk',
    appId: '1:774218376929:web:a97a3f5892e78c636a79a0',
    messagingSenderId: '774218376929',
    projectId: 'proyecto-e5520',
    authDomain: 'proyecto-e5520.firebaseapp.com',
    storageBucket: 'proyecto-e5520.appspot.com',
    measurementId: 'G-YCDZ0GQM6N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1JYhD_pTgJ_lgDs3CVQy86EZs-XY7U6k',
    appId: '1:774218376929:android:ccbdcb881e772e316a79a0',
    messagingSenderId: '774218376929',
    projectId: 'proyecto-e5520',
    storageBucket: 'proyecto-e5520.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCapQReodEh0MIpmnmWs-0PWwtIjfrgt2w',
    appId: '1:774218376929:ios:d9c1c504b475d0ac6a79a0',
    messagingSenderId: '774218376929',
    projectId: 'proyecto-e5520',
    storageBucket: 'proyecto-e5520.appspot.com',
    iosClientId: '774218376929-rg5vhmkpqiqhcu3rif7nq9e6oh8v6mjb.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyecto',
  );
}
